// <auto-generated />
using System;
using FuriaAPP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuriaAPP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250425014613_AtualizarCampeonatoModel")]
    partial class AtualizarCampeonatoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FuriaAPP.API.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.JogoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adversario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdversarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoAdversario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoFuria")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("jogoHistoricos");
                });
#pragma warning restore 612, 618
        }
    }
}
