// <auto-generated />
using System;
using FuriaAPP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuriaAPP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250426021725_CreateUsuarioJogoInteresse")]
    partial class CreateUsuarioJogoInteresse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FuriaAPP.API.Models.Adversario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adversarios");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.JogoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adversario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdversarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoAdversario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoFuria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("jogoHistoricos");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Usuario.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Usuario.UsuarioJogoInteresse", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "JogoId");

                    b.HasIndex("JogoId");

                    b.ToTable("jogoJogoInteresse");
                });

            modelBuilder.Entity("Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogoHistoricoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemporadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("JogoHistoricoId");

                    b.HasIndex("JogoId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.JogoHistorico", b =>
                {
                    b.HasOne("Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Usuario.UsuarioJogoInteresse", b =>
                {
                    b.HasOne("FuriaAPP.API.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuriaAPP.API.Models.Usuario.Usuario", "Usuario")
                        .WithMany("JogosDeInteresse")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Noticia", b =>
                {
                    b.HasOne("FuriaAPP.API.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId");

                    b.HasOne("FuriaAPP.API.Models.JogoHistorico", "JogoHistorico")
                        .WithMany()
                        .HasForeignKey("JogoHistoricoId");

                    b.HasOne("FuriaAPP.API.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId");

                    b.HasOne("Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId");

                    b.Navigation("Campeonato");

                    b.Navigation("Jogo");

                    b.Navigation("JogoHistorico");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("Temporada", b =>
                {
                    b.HasOne("FuriaAPP.API.Models.Campeonato", "Campeonato")
                        .WithMany("Temporadas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Campeonato", b =>
                {
                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("FuriaAPP.API.Models.Usuario.Usuario", b =>
                {
                    b.Navigation("JogosDeInteresse");
                });
#pragma warning restore 612, 618
        }
    }
}
